version: "3"

services:
    nginx:
        build:
            context: ./
            dockerfile: .docker/nginx/Dockerfile
        restart: always
        volumes:
            - public:/var/www/html/public:ro
        depends_on:
            - php

    php:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        env_file: .env
        restart: always
        volumes:
            - public:/var/www/html/public:ro

volumes:
    public:
