version: "3"

services:
  nginx:
    networks:
      - default
      - web

  php:
    networks:
      - default
      - db

networks:
  web:
    external: true
    name: web
  db:
    external: true
    name: db
