version: "3"

services:
    nginx:
        image: registry.digitalocean.com/claudesky/claudekirkecom_nginx
        build:
            context: ./
            dockerfile: .docker/nginx/Dockerfile
        env_file: .env
        restart: always
        depends_on:
            - php

    php:
        image: registry.digitalocean.com/claudesky/claudekirkecom_php
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        env_file: .env
        restart: always
