version: "3"

services:
    nginx:
        build:
            context: ./
            dockerfile: .docker/nginx/Dockerfile
        env_file: .env
        restart: always
        depends_on:
            - php

    php:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        env_file: .env
        restart: always
