name: Run Tests
on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Cache NPM packages
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install node dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Copy .env.example into .env
      run: cp .env.example .env

    - name: Generate encryption key
      run: ./artisan key:generate

    - name: Link storage directories
      run: ./artisan storage:link --relative
      
    - name: Build js and css
      run: npm run dev

    - name: Run test suite
      run: ./artisan test
    
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
          name: laravel-failure-artifact
          path: storage/logs/laravel.log
